"""TicketEvent model."""

import uuid
from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING

from sqlalchemy import JSON, DateTime, ForeignKey, Index, Uuid
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.mixins import utcnow

if TYPE_CHECKING:
    from app.models.ticket import Ticket
    from app.models.user import User


class TicketEventType(StrEnum):
    """Kind of thing that happened to a ticket."""

    TICKET_CREATED = "TICKET_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    ASSIGNED = "ASSIGNED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    AI_CLASSIFIED = "AI_CLASSIFIED"


# JSONB on PostgreSQL, portable JSON elsewhere (the SQLite test suite).
_JSON_TYPE = JSON().with_variant(JSONB(), "postgresql")


class TicketEvent(db.Model):
    """An append-only record of something relevant that happened to a ticket.

    Events are the audit trail of a ticket. ``actor_id`` is nullable
    because a future event may be generated by the system or the AI
    classifier rather than by a person. The payload column is named
    ``metadata`` in SQL but ``data`` in Python because ``metadata`` is a
    reserved name in SQLAlchemy declarative models.
    """

    __tablename__ = "ticket_events"
    __table_args__ = (
        Index("ix_ticket_events_ticket_created_at", "ticket_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(), primary_key=True, default=uuid.uuid4
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(), ForeignKey("tickets.id", ondelete="RESTRICT"), nullable=False
    )
    actor_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(), ForeignKey("users.id", ondelete="RESTRICT"), nullable=True
    )
    event_type: Mapped[TicketEventType] = mapped_column(
        SAEnum(
            TicketEventType,
            name="ticket_event_type",
            native_enum=False,
            create_constraint=True,
        ),
        nullable=False,
    )
    data: Mapped[dict] = mapped_column(
        "metadata", _JSON_TYPE, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False
    )

    ticket: Mapped["Ticket"] = relationship("Ticket", back_populates="events")
    actor: Mapped["User | None"] = relationship(
        "User", back_populates="events"
    )
